export const SET_ACTIVE_ROUTE = "SET_ACTIVE_ROUTE";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
export const CLEAR_ACTIVE_USER = "CLEAR_ACTIVE_USER";

export const DIALOG_OPEN = "@ui/DIALOG_OPEN";
export const DIALOG_CLOSE = "@ui/DIALOG_CLOSE";
export const DIALOG_ALL_CLOSE = "@ui/DIALOG_ALL_CLOSE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const SOCIAL_LOGIN_REQUEST = "SOCIAL_LOGIN_REQUEST";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE";

export const LOAD_LINKEDIN_REQUEST = "LOAD_LINKEDIN_REQUEST";
export const LOAD_LINKEDIN_FAILURE = "LOAD_LINKEDIN_FAILURE";
export const LOAD_LINKEDIN_SUCCESS = "LOAD_LINKEDIN_SUCCESS";

export const PASSWORD_RESET_REQUEST_REQUEST = "PASSWORD_RESET_REQUEST_REQUEST";
export const PASSWORD_RESET_REQUEST_SUCCESS = "PASSWORD_RESET_REQUEST_SUCCESS";
export const PASSWORD_RESET_REQUEST_FAILURE = "PASSWORD_RESET_REQUEST_FAILURE";

export const PASSWORD_RESET_CONFIRM_REQUEST = "PASSWORD_RESET_CONFIRM_REQUEST";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAILURE = "PASSWORD_RESET_CONFIRM_FAILURE";

export const JOB_DETAIL_REQUEST = "JOB_DETAIL_REQUEST";
export const JOB_DETAIL_SUCCESS = "JOB_DETAIL_SUCCESS";
export const JOB_DETAIL_FAILURE = "JOB_DETAIL_FAILURE";
